services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Service\Security\User\Authentication\Login\:
        resource: '%kernel.project_dir%/src/AppBundle/Service/Security/User/Authentication/Login/*'