# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_USER:   IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:   ROLE_USER

    providers:
        user_provider:
            entity:
                class: 'AppBundle:User'
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: app_user_authentication_authenticate
                check_path: app_user_authentication_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   app_user_authentication_logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            user_checker: AppBundle\Service\Security\User\Authentication\Login\LoginChecker
